server:
  port: 8041
spring.cloud.stream.function.definition: process;purchasesprocess;ordersprocess;


spring.cloud.stream.bindings.ordersprocess-in-0:
  destination: orders
spring.cloud.stream.bindings.ordersprocess-in-1:
  destination: product-feed
spring.cloud.stream.bindings.ordersprocess-out-0:
  destination: order-validations
spring.cloud.stream.kafka.streams.bindings.ordersprocess-out-0:
  producer:
    keySerde: org.apache.kafka.common.serialization.StringSerializer
#spring.cloud.stream.bindings.purchasesprocess-in-0:
#  destination: purchase-events
#spring.cloud.stream.bindings.purchasesprocess-in-1:
#  destination: product-feed
#spring.cloud.stream.bindings.purchasesprocess-out-0:
#  destination: purchase-counts
#spring.cloud.stream.kafka.streams.bindings.purchasesprocess-in-0:
#  consumer:
#    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#spring.cloud.stream.kafka.streams.bindings.purchasesprocess-in-1:
#  consumer:
#    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    materializedAs: all-purchases
#spring.cloud.stream.kafka.streams.bindings.purchasesprocess-out-0:
#  producer:
#    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#    valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde



#spring.cloud.stream.bindings.process-in-0:
#  destination: purchase-events
#spring.cloud.stream.bindings.process-in-1:
#  destination: product-feed
#spring.cloud.stream.kafka.streams.bindings.process-in-0:
#  consumer:
#    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#spring.cloud.stream.kafka.streams.bindings.process-in-1:
#  consumer:
#    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#    materializedAs: all-products


spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    schema.registry.url: http://localhost:8081
    commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.autoAddPartitions: true
spring.cloud.stream.kafka.streams.binder.minPartitionCount: 4
spring.cloud.stream.kafka.streams.binder.configuration.application.server: localhost:8080
spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
spring.application.name: kafka-streams-iq-advanced-sample