version: '2'
services:
  productDB:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    container_name: productDB
    ports:
      - 5433:5432

  mongodb-order:
    image: mongo:3.4.22-xenial
    ports:
      - 27017:27017
    container_name: mongosdb


